language: php

sudo: false

php:
  - 7.0
  - 7.1

env:
  global:
    - DB_DATABASE=travis
    - DB_USERNAME=root
    - DB_PASSWORD=

before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.example .env
  - composer self-update
  - composer install --prefer-source --no-interaction
  - php artisan key:generate
  - php artisan migrate --seed --no-interaction -vvv

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_script: php vendor/bin/coveralls

services:
  - mysql