language: php

sudo: false

php:
  - 7.0
  - 7.1

env:
  global:
    - APP_ENV=testing
    - APP_DEBUG=true
    - APP_KEY=base64:R5lB7f1s3e+wtDAOIx1+4kextwoI6zoLNf8TfaOLExM=
    - DB_CONNECTION=sqlite
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.example .env
  - composer self-update
  - composer install --prefer-source --no-interaction
  - php artisan key:generate
  - php artisan migrate --seed --no-interaction -vvv

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml